### ISSUE TITLE
Plugin not working with Jellyfin 10.3.7 

### ISSUE THREAD

**Issue by cfredericksen** [jesseward/jellyfin-plugin-lastfm#10]
Error after upgrading Jellyfin Docker image.

I tried removing and reinstalling the plugin and same error. Worked great on previous Jellyfin version.
```
[09:00:54] [ERR] Error in last.fm
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String artist, String album, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String artist, String album, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(AlbumInfo item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[09:00:54] [ERR] Error in last.fm
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String musicbraizId, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String musicbraizId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(AlbumInfo item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[09:00:55] [ERR] Error in last.fm
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String artist, String album, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(String artist, String album, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetAlbumResult(AlbumInfo item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by jesseward** [comment]
thanks for reporting. Likely an API change in Jellyfin core. 

Will take a look this week

**Comment by jesseward** [comment]
Fixed in PR https://github.com/jesseward/jellyfin-plugin-lastfm/pull/11

Thanks @majora2007
