### ISSUE TITLE
Method not found: Void MediaBrowser.Common.Net.HttpRequestOptions.set_LogRequest(Boolean)

### ISSUE THREAD

**Issue by maximtrp** [jesseward/jellyfin-plugin-lastfm#15]
Thank you for this plugin! Been using it with Jellyfin 10.3.7, but after update to 10.4.0 it has stopped working. Here is the log from `journalctl`:

```
Oct 16 08:17:08 orangepipc docker[1441]: [05:17:08] [ERR] Error processing request
Oct 16 08:17:08 orangepipc docker[1441]: System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_LogRequest(Boolean)'.
Oct 16 08:17:08 orangepipc docker[1441]:    at Jellyfin.Plugin.Lastfm.Api.BaseLastfmApiClient.Post[TRequest,TResponse](TRequest request)
Oct 16 08:17:08 orangepipc docker[1441]:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
Oct 16 08:17:08 orangepipc docker[1441]:    at Jellyfin.Plugin.Lastfm.Api.BaseLastfmApiClient.Post[TRequest,TResponse](TRequest request)
Oct 16 08:17:08 orangepipc docker[1441]:    at Jellyfin.Plugin.Lastfm.Api.LastfmApiClient.RequestSession(String username, String password)
```

Jellyfin Last.fm Plugin version is 2.0.1.

**Comment by jesseward** [comment]
Thanks for reporting. Likely an API change in core Jellyfin in the 10.4.0 release. Will take a look soon

**Comment by jesseward** [comment]
Looks to have been removed from `HttpRequestOptions` in commit: https://github.com/jellyfin/jellyfin/commit/5eaf5465a55df0359f85077b7922ca4a45681831#diff-27389fa63ee57e081bdad8fc860dcb14L82

**Comment by jesseward** [comment]
Published https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/v3.0.0
