### ISSUE TITLE
Fails to load under 10.6.0 nightlies

### ISSUE THREAD

**Issue by KristupasSavickas** [jesseward/jellyfin-plugin-lastfm#18]
```
[2020-05-28 10:57:28.745 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Lastfm, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Lastfm/Jellyfin.Plugin.Lastfm.dll"
[2020-05-28 10:57:28.746 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Playback Reporting/Jellyfin.Plugin.PlaybackReporting.dll"
[2020-05-28 10:57:28.747 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "/config/data/plugins/Kodi Sync Queue/LiteDB.dll"
[2020-05-28 10:57:28.748 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Kodi Sync Queue/Jellyfin.Plugin.KodiSyncQueue.dll"
[2020-05-28 10:57:28.749 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Trakt, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Trakt/Trakt.dll"
[2020-05-28 10:57:30.812 +03:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Plugin"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Plugin'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-05-28 10:57:30.821 +03:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.KodiSyncQueue.Plugin"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.Plugin'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-05-28 10:57:31.170 +03:00] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-05-28 10:57:31.749 +03:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-05-28 10:57:31.749 +03:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by KristupasSavickas** [comment]
This PR seems to be the cause of this: https://github.com/jellyfin/jellyfin/pull/3098

**Comment by jesseward** [comment]
@KristupasSavickas thanks for reporting. Will refactor the logger asap.

**Comment by joytrekker** [comment]
10.6.0 released today. Looks like the last.fm plugin needs a json manifest now. The plugin fails to appear in the dashboard. See https://jellyfin.org/posts/plugin-updates/

**Comment by anthonylavado** [comment]
The manifest is only if you want to have direct updates inside Jellyfin :-)

@Jesseward let us know if you need a hand with the update :-)

(I am from Jellyfin's Core Team)

**Comment by joytrekker** [comment]
@anthonylavado Thanks. I thought the manifest was needed to enable the plugin too. Is there any plan to add official support for last.fm / listenbrainz?

**Comment by anthonylavado** [comment]
@joytrekker To be honest, we're spread a bit thin on maintaining our own plugins, so community contributions are appreciated. With this new system in 10.6.0, people can add custom plugin catalogues (that's what the manifest does), and then you don't have to wait on us to update plugins.

As far as providers/scrobblers go, we actually plan on turning each of them into a plug-in. This keeps the main server lightweight, and you don't have to install services you don't want. It's a long term plan though.

**Comment by jesseward** [comment]
> The plugin fails to appear in the dashboard. See https://jellyfin.org/posts/plugin-updates/

Thanks for this pointer @joytrekker . I have applied the changes noted within that update post, and am scrobbling on 10.6.0

```
[2020-07-24 04:01:41.593 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Lastfm, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Jellyfin.Plugin.Lastfm.dll"
[2020-07-24 04:02:08.991 +00:00] [INF] [4] Jellyfin.Plugin.Lastfm.ServerEntryPoint: "jw76" is now playing artist="Nightmares on Wax", track="Nights Introlude", album="Smokers Delight"
[2020-07-24 04:05:20.350 +00:00] [INF] [20] Jellyfin.Plugin.Lastfm.ServerEntryPoint: "jw76" played artist="Nightmares on Wax", track="Nights Introlude", album="Smokers Delight"
```

> @jesseward let us know if you need a hand with the update :-)

thanks, @anthonylavado . I have followed the changes from the plugin update post and have a new build forthcoming. I see that there is a mailing list for notifications. I will reach out and ensure I am subscribed there.

**Comment by anthonylavado** [comment]
@jesseward Send me a message through apps@jellyfin.org and I'll get you added.

**Comment by jesseward** [comment]
> @jesseward Send me a message through [apps@jellyfin.org](mailto:apps@jellyfin.org) and I'll get you added.

Thanks will reach out soon.

**Comment by jesseward** [comment]
Posted at https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/5.0.0

**Comment by KristupasSavickas** [comment]
Thanks for all the work!

Would it be possible to have a plugin repository for this or maybe even to have it added to the official jellyfin plugins list?

**Comment by jesseward** [comment]
> Thanks for all the work!
> 
> Would it be possible to have a plugin repository for this or maybe even to have it added to the official jellyfin plugins list?

sure @KristupasSavickas , keep an eye on https://github.com/jesseward/jellyfin-plugin-lastfm/issues/22
