### ISSUE TITLE
System.MissingMethodException: Method not found GetProviderId

### ISSUE THREAD

**Issue by jesseward** [jesseward/jellyfin-plugin-lastfm#19]
Nightly docker image (10.6 branch) changes API. 
```c#
[2020-07-10 01:04:06.222 +00:00] [ERR] [25] MediaBrowser.Providers.Manager.ProviderManager: "LastfmImageProvider" failed in GetImageInfos for type "MusicAlbum"
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Entities.ProviderIdsExtensions.GetProviderId(MediaBrowser.Model.Entities.IHasProviderIds, MediaBrowser.Model.Entities.MetadataProviders)'.
   at Jellyfin.Plugin.Lastfm.Providers.LastfmImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```

Some changes mentioned in https://github.com/jellyfin/jellyfin/issues/3400

**Comment by EmeraldSnorlax** [comment]
Just want to chime in and say that this now affects stable Jellyfin (10.6.0); the plugin is in the same location, but no longer appears in the plugins tab of settings, where it did in the past

```
[2020-07-23 14:39:36.061 +00:00] [INF] Loading assemblies
[2020-07-23 14:39:36.144 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Lastfm, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Jellyfin.Plugin.Lastfm.dll"
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"ActivityLog"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"ImageInfo"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"Permission"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"Preference"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:38.216 +00:00] [WRN] The entity type '"User"' is configured to use schema '"jellyfin"'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2020-07-23 14:39:39.720 +00:00] [ERR] Error creating "Jellyfin.Plugin.Lastfm.Plugin"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Plugin'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-07-23 14:39:40.525 +00:00] [ERR] Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-07-23 14:39:40.526 +00:00] [ERR] Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by jesseward** [comment]
here there @EmeraldSnorlax there was a version posted last night that should address the 10.6.0 issues .

See https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/5.0.0 and https://github.com/jesseward/jellyfin-plugin-lastfm/issues/18

**Comment by EmeraldSnorlax** [comment]
Sorry, I only just saw that thread, deleted original comment.

**Comment by jesseward** [comment]
Fixed with https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/5.0.0.1 

The README.md now includes information on how to keep up to date and use the 3rd party LastFM plugin repo as well.
