### ISSUE TITLE
ILogger error while loading plugin

### ISSUE THREAD

**Issue by silktrader** [jesseward/jellyfin-plugin-lastfm#21]
I am unable to use the plugin (4.0.0) while on Windows 10 due to the ILogger's service injection not being resolved, possibly because of missing assemblies (?).

```[2020-07-23 13:54:51.356 +02:00] [INF] [1] Main: Jellyfin version: "10.6.0"
[2020-07-23 13:54:51.384 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-07-23 13:54:51.389 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-07-23 13:54:51.391 +02:00] [INF] [1] Main: Architecture: X64
[2020-07-23 13:54:51.394 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-07-23 13:54:51.395 +02:00] [INF] [1] Main: User Interactive: True
[2020-07-23 13:54:51.397 +02:00] [INF] [1] Main: Processor count: 4
[2020-07-23 13:54:51.639 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-07-23 13:54:51.653 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Lastfm, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Lastfm\Jellyfin.Plugin.Lastfm.dll"
[2020-07-23 13:54:55.398 +02:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Plugin"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Plugin'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-07-23 13:54:55.795 +02:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmAlbumProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-07-23 13:54:55.802 +02:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.Lastfm.Providers.LastfmArtistProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by jesseward** [comment]
hey there, this is likely related to https://github.com/jesseward/jellyfin-plugin-lastfm/issues/18 .

I am pushing a new build 5.0.0 this evening.
