### ISSUE TITLE
Unable to install from repository

### ISSUE THREAD

**Issue by Derkades** [jesseward/jellyfin-plugin-lastfm#32]
Steps:
- Add repository link from readme file
- In catalog select LastFM
- Select version 7.0.0.0 and click install
- Accept jellyfin plugin warning
- Observe infinite spinner

Log
```
[13:35:53] [ERR] [171] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://mydomain/Packages/Installed/LastFM?AssemblyGuid=5e7fe7f0-b048-429e-a431-b1a7e69c930d&version=7.0.0.0
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: LastFM
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
Using jellyfin 10.6.4

**Comment by Derkades** [comment]
Installing version 6.0.0.3 worked, I guess 7.0.0.0 is only compatible with 10.7

**Comment by hisakiyo** [comment]
Thanks a lot, I had the same problem and it works with version 6.0.0.3 :)

**Comment by jesseward** [comment]
thanks for reporting this @Derkades and @hisakiyo . This is interesting as the plugin metadata includes a `targetAbi` version for each release. This seems like a bug within Jellyfin plugin loader ecosystem, that it is ignoring this value.

```json
      {
        "version": "7.0.0.0",
        "changelog": "Jellyfin LastFM build v7.0.0.0",
        "targetAbi": "10.7.0.0",
        "sourceUrl": "https://github.com/jesseward/jellyfin-plugin-lastfm/releases/download/7.0.0.0/lastfm_7.0.0.0.zip",
        "checksum": "d6dbcf63760c7de4d09813a4c6f78361",
        "timestamp": "2021-01-25T00:57:19Z"
      },
```

I will raise this with Jellyfin core team ...
