### ISSUE TITLE
Plugin does not work anymore with jellyfin 10.9.0

### ISSUE THREAD

**Issue by bmillemathias** [jesseward/jellyfin-plugin-lastfm#63]
Hello,

First of all thanks for the plugin.
that would be super great if you could update it,

Best

error in the logs
```
[05:51:07] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/LastFM_8.0.0.4/home/runner/work/jellyfin-plugin-lastfm/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm/bin/Debug/net6.0/Jellyfin.Plugin.Lastfm.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by jesseward** [comment]
A new release was published at https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/8.1.0.0 .

You can install via the plugin repo, or install directly from the GitHub release page. If JF doesn't prompt for an upgrade, try removing the plugin and reinstalling via the plugin repo selector.

**Comment by magandrez** [comment]
Works in my setup. Thanks @jesseward

**Comment by bmillemathias** [comment]
works fine for me too, thanks.
i close the issue

**Comment by DoogeJ** [comment]
Can confirm this absolutely works. Thanks so much for the speedy update! ♥
